dry_run: true
max_slippage_bps: 100
poll_interval_seconds: 15
positions:
- already_in_position: true
  amount_in_sol: 0.005
  entry_price: 2.667e-12
  sold: true
  stop_loss_pct: 15
  take_profit_pct: 25
  token_balance: 0
  token_mint: CmGsBfi3Zbsygpt1FcvFcQa3mD2drYGX6w5WdsWZpump
  token_symbol: CMGS
- already_in_position: true
  amount_in_sol: 0.001
  entry_price: 8.02e-13
  sold: true
  stop_loss_pct: 15
  take_profit_pct: 25
  token_balance: 0
  token_mint: HziPQunVCQN6Knjxv96pEjqLxpJsZ7KFvHGV7TVEpump
  token_symbol: HZIP
- already_in_position: true
  amount_in_sol: 0.01
  entry_price: 4.884081037502868e-12
  sold: false
  stop_loss_pct: 5
  take_profit_pct: 25
  token_balance: 2047468075
  token_mint: HFq1GAEfsFamEQYVccRemH37qWR1VgSJZPxdVGYVpump
  token_symbol: NOVA
rpc_url: https://api.mainnet-beta.solana.com
